### ISSUE TITLE
Installing Themes?

### ISSUE THREAD

**Issue by DanielSokil** [ketchuphq/ketchup#12]
![screenshot_20180422-234449](https://user-images.githubusercontent.com/24403355/39106062-47d8fa46-4687-11e8-9770-f4a81d1b4c0f.jpg)

**Comment by octavore** [comment]
I've added more content to the theme installation page, but it's still a work in progress. Currently there's some support for an external registry.json file with a list of third-party themes, but the focus is mainly on providing support for your own themes which you've cloned into `data/themes/$themeName`. Closing this ticket for now since there's no action to take.
